name: 🐍 Kobra Sunset Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositori
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install matplotlib numpy

      - name: Generate kobra SVG
        uses: Platane/snk@v3
        with:
          github_user_name: WahyuSatrio505
          outputs: |
            ./output/kobra-sunset-animation.svg?palette=github-dark

      - name: Commit dan Push hasil
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add output/kobra-sunset-animation.svg
          git commit -m "update: kobra sunset animation"
          git push
